name: Feature Request
description: Suggest a new feature or enhancement for Git ADR VS Code extension
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe it here.
      placeholder: |
        I'm always frustrated when...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: |
        I would like the extension to...
        This could work by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        I've tried...
        Another option could be...

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Which part of the extension does this affect?
      options:
        - Tree View / UI
        - ADR Creation/Editing
        - Search Functionality
        - Git Integration / Sync
        - CLI Integration
        - Settings / Configuration
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority (from your perspective)
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical / Blocking
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, examples, or additional information.
